### ISSUE TITLE
Role set to none on user connection

### ISSUE THREAD

**Issue by julienlusson** [uhm-coe/authorizer#46]
I've a problem on a multisite install with the latest version of Authorizer (tested on a fresh install of Wordpress 4.9.1 without any other plugin).

When I add an user in Wordpress to a site (not in authorizer) with the "contributor" status for example, when the user try to login on the site with CAS, the role of the user is set to "None" in Wordpress.

**Comment by pkarjala** [comment]
Hi @julienlusson thanks for the report!

We are able to reproduce this in our test instances.  In this case, the user should get assigned the same role in Authorizer that they were assigned when their account was created.

Marking as bug and will begin work on resolution.

**Comment by pkarjala** [comment]
@julienlusson This should now be fixed, and will be pushed to the WordPress plugin repo with our next version release.  Thank you again for the report!

**Comment by julienlusson** [comment]
Thanks but in fact, my bug wasn't resolved, but I've found why!

The user is already in multisite but not on this site, so the problem was present in a different hook: "added_existing_user".

In the function "add_existing_user_to_authorizer_when_created_noconfirmation()", I've found that this code doesn't work:
`$this->add_user_to_authorizer_when_created( $user->user_email, $user->user_registered, $user->user_roles );`

If I change with that it works (in Wordpress 4.9.1):
$this->add_user_to_authorizer_when_created( $user->user_email, $user->user_registered, $user->roles );

"$user->user_roles" in present in 4 places in the code, I've not tested the 3 others cases.

**Comment by figureone** [comment]
Thanks! No idea how that bug snuck through our testing. Will get a fix out shortly.

**Comment by figureone** [comment]
Version 2.7.1 has been released: https://wordpress.org/plugins/authorizer/#developers
